version: "3.9"

services:
  dev:
    image: ubuntu:22.04
    container_name: ubuntu-dev-runner
    working_dir: /workspace
    stdin_open: true
    tty: true

    # only mount docker socket if you need docker inside container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "64000:8080"
      - "64001:8081"
    environment:
      - DEBIAN_FRONTEND=noninteractive

    entrypoint: >
      bash -c "
        apt-get update &&
        apt-get install -y git make docker.io &&
        # clone SecureDrop into workspace if not already there
        if [ ! -d /workspace/securedrop ]; then
          git clone https://github.com/freedomofpress/securedrop.git /workspace/securedrop
        fi &&
        echo 'Container ready. Run: cd /workspace/securedrop && make dev' &&
        bash
      "

    networks:
      - mynet

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - nginx-not-tor
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TOKEN} # securedrop-dev-0
    networks:
      - mynet

  tor:
    build:
      context: ./tor
    container_name: tor-hidden-service
    restart: unless-stopped
    volumes:
      - tor_data:/var/lib/tor

  nginx-tor:
    image: nginx:alpine
    container_name: hidden-web
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro

  nginx-not-tor:
    image: nginx:alpine
    container_name: public-landing
    restart: unless-stopped
    depends_on:
      - tor
    volumes:
      - ./public/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html
      - tor_data:/tor   # 👈 read onion data
    ports:
      - "${HOST_PORT}:80"
    command: >
      sh -c "
      echo 'Waiting for onion address...' &&
      while [ ! -f /tor/hidden_service/hostname ]; do
        sleep 2
      done &&
      echo \"$(cat /tor/hidden_service/hostname)\" &&
      export ONION_ADDRESS=\"$(cat /tor/hidden_service/hostname)\" &&
      echo $$ONION_ADDRESS &&
      envsubst '$$ONION_ADDRESS' < /usr/share/nginx/html/index.html > /usr/share/nginx/html/index.final.html &&
      nginx -g 'daemon off;'
      "
    networks:
      - mynet

      
volumes:
  tor_data:
# run this and then attach the containers to it so we can test serve
networks:
  mynet: